---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
spec:
  replicas: 2
  selector:
    matchLabels:
      cicd: helm-1
  template:
    metadata:
      labels:
        cicd: helm-1
    spec:
      containers:
        - name: container-1
          image: prathima77/zomato-app:zomatoimage
          ports:
            - containerPort: 3000
